name: publish
on: [push]
jobs:
  publish-pymc3-docker:
    name: Does this need a name
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_CONTAINER_PAT }}
      - name: Build the Docker Image
        run: |
          docker build . --tag ghcr.io/cormach/pymc3-docker:latest
          docker run ghcr.io/cormach/pymc3-docker:latest
          docker push ghcr.io/cormach/pymc3-docker:latest
